name: Ruff Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ruff:
    name: Ruff (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Continues running on Windows even if Linux fails (or vice versa)
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          args: "check . --output-format=github"

      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check ."
